### ISSUE TITLE
Homepage not responsive

### ISSUE THREAD

**Issue by rishi11** [ameym06/CS5610-ameym06#11]
Please make your homepage responsive. Please keep in mind that you  are not allowed to use bootstrap on your homepage.

**Comment by ameym06** [comment]
I checked the homepage. I think it is responsive. Can you please let me know what exactly did you feel was wrong so that I can rectify that. Waiting for your response.

**Comment by ameym06** [comment]
Implemented additional media queries for making the homepage even more responsive
